MAX_COMPONENTS = 64
MAX_ENTITIES = 256
MILLISECONDS = 1000
FPS = 30
FRAME_DURATION = FPS / MILLISECONDS
MAX_FRAME_SKIP = FRAME_DURATION * 5

# Message Subjects
REGISTER_SYSTEM = 'REGISTER SYSTEM'
UPDATE = 'UPDATE'
CREATE_ENTITY = 'CREATE ENTITY'
DESTROY_ENTITY = 'DESTROY ENTITY'
CREATE_COMPONENT = 'CREATE COMPONENT'
DESTROY_COMPONENT = 'DESTROY COMPONENT'
